name: "PMod 7 Segment Display"

on:
  schedule:
    - cron: "0 8 * * 1"
  
  pull_request:
    paths:
      - 'kibot.yml'
      - '.github/workflows/pmod_7segment.yml'
      - 'PMod_7Segment/hardware/*.kicad_sch'
      - 'PMod_7Segment/hardware/*.kicad_pcb'
      - 'PMod_7Segment/Firmware/*'
      - 'PMod_7Segment/Software/*'
      
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Fabrication:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: INTI-CMNB/KiBot@v2_k6
      with:
        # Required - kibot config file
        config: kibot.yml
        # optional - prefix to output defined in config
        dir: Hardware/Fabrication
        # optional - schematic file
        schema: 'PMod_7Segment/hardware/PMod_7Segement.kicad_sch'
        # optional - PCB design file
        board: 'PMod_7Segment/hardware/PMod_7Segement.kicad_pcb'

    - name: Retrieve results
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: Fabrication_Files
        path: |
          Hardware/Fabrication/
        if-no-files-found: warn

  Build-Software:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          path: project

      - name: Checkout Pico SDK
        uses: actions/checkout@v2
        with:
          repository: raspberrypi/pico-sdk
          path: pico-sdk
          submodules: true

      - name: Install deps
        run: |
          sudo apt update && sudo apt install cmake gcc-arm-none-eabi libnewlib-arm-none-eabi libstdc++-arm-none-eabi-newlib

      - name: Make directory
        run: |
          mkdir project/PMod_7Segment/Software/build

      - name: Build
        working-directory: project/PMod_7Segment/Software/build
        shell: bash
        run: |
          PICO_SDK_PATH=../../../pico-sdk cmake ..
          make

      - name: Retrieve results
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: RP_Pico_Files
          path: |
            project/PMod_7Segment/Software/build/*.uf2
          if-no-files-found: warn
  Build-Firmware:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          path: project

      - name: Install verilator tools
        run: |
          sudo apt-get install git perl python3 make autoconf g++ flex bison ccache
          sudo apt-get install libgoogle-perftools-dev numactl perl-doc
          sudo apt-get install libfl2  # Ubuntu only (ignore if gives error)
          sudo apt-get install libfl-dev  # Ubuntu only (ignore if gives error)
          sudo apt-get install zlibc zlib1g zlib1g-dev  # Ubuntu only (ignore if gives error)
          sudo apt-get install lcov
          wget https://github.com/sifive/verilator/releases/download/4.204-0sifive3/verilator_4.204-0sifive3_amd64.deb
          sudo dpkg -i verilator_4.204-0sifive3_amd64.deb

      - name: Run coverage
        working-directory: project/PMod_7Segment/Firmware
        run: |
          export VINC=/usr/share/verilator/include
          make test

      - name: Checkout vcd2json
        uses: actions/checkout@v2
        with:
          repository: nanamake/vcd2json
          path: vcd2json

      - name: Generate plot of the waveform
        working-directory: project/PMod_7Segment/Firmware
        run: |
          sed -i '/^$/d' trace.vcd
          python3 generate_wave.py


      - name: Extract the test data
        working-directory: project/PMod_7Segment/Firmware
        run: |
          echo 'Testing Output:' >> test-results.txt
          echo -n '<img src="https://svg.wavedrom.com/' >> test-results.txt
          sed -i "s/\"/'/g" trace.json
          echo '"/>' >> trace.json
          cat trace.json | tr -d '\n' >> test-results.txt
          echo 'Coverage Stats:' >> test-results.txt
          echo '```'  >> test-results.txt
          cat logs/coverage.txt >> test-results.txt
          echo '```'  >> test-results.txt

      - name: comment test results in PR
        if: github.event.schedule != '0 8 * * 1'
        uses: machine-learning-apps/pr-comment@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          path: project/PMod_7Segment/Firmware/test-results.txt

      - name: Install deps
        run: |
          sudo -H pip3 install yowasp-yosys
          sudo -H pip3 install yowasp-nextpnr-ice40-all
           # Runs a set of commands using the runners shell

      - name: Run yosys on the files
        working-directory: project/PMod_7Segment/Firmware
        run: |
          yowasp-yosys -p 'synth_ice40 -top top -json pixel.json' top.v writepixels.v

      - name: Run nextpnr on the files
        working-directory: project/PMod_7Segment/Firmware
        run: |
          yowasp-nextpnr-ice40 --up5k --package sg48 --json pixel.json --pcf icebreaker.pcf --asc pixel.asc --log nextpnr.log
          yowasp-icepack pixel.asc pixel.bin

      - name: Retrieve results
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: Ice40_5K_Firmware
          path: |
            project/PMod_7Segment/Firmware/pixel.bin
            project/PMod_7Segment/Firmware/trace.vcd
          if-no-files-found: warn

      - name: Extract the stats from the build log file
        working-directory: project/PMod_7Segment/Firmware
        run: |
          echo 'Info: FPGA Place and Route statistics:' > utilisation.txt
          echo 'Info:```' >> utilisation.txt
          awk '/Info: Logic utilisation before packing:/' RS= nextpnr.log >> utilisation.txt
          echo 'Info: ' >> utilisation.txt
          awk '/Total DFFs:/' RS= nextpnr.log  >> utilisation.txt
          echo 'Info: ' >> utilisation.txt
          awk '/Info: Device utilisation:/' RS= nextpnr.log >> utilisation.txt
          echo 'Info: ' >> utilisation.txt
          grep "MHz" nextpnr.log | tail -1  >> utilisation.txt
          echo 'Info:```' >> utilisation.txt
          sed 's/^.\{5\}//' utilisation.txt >results.txt
          rm utilisation.txt

      - name: comment PR
        if: github.event.schedule != '0 8 * * 1'
        uses: machine-learning-apps/pr-comment@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          path: project/PMod_7Segment/Firmware/results.txt

